ungrouped:
  hosts:
    controller:
      ansible_connection: local
    main:
      ansible_host: 172.21.1.2
      ansible_ssh_private_key_file: /home/vagrant/vagrant/.vagrant/machines/main/libvirt/private_key
target_hosts:
  hosts:
    main:
